integration specs for views and fix n+1 problems
Oklukeok/Blog-App pull request #6
Opened 2023-02-08 15:42 UTC by Oklukeok

### **_Features:_**
- Solved the N+1 problem when fetching all posts and their comments for a user.
- (Didn't use bullet gem).
- Created integration test with Capybara for:
  - User index page.
  - user show page.
  - User post index page.
  - Post show page.
 
### **_Logs:_**

**Before:**

![image](https://user-images.githubusercontent.com/93407216/217576242-6fc5af2d-ccd8-4492-91ac-ed1dcb3816ad.png)

**After:**

![image](https://user-images.githubusercontent.com/93407216/217575517-2e11b528-b7cc-4bf2-b202-f6779f8ce58a.png)

**Capybara testing:**

![image](https://user-images.githubusercontent.com/93407216/217578075-83d1553f-ff05-4062-bee0-30153ef09552.png)

2023-02-08 17:02 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi team 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Integration specs 📌 
✔️ Good commit history
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

- [ ] All the integration tests seem to be failing. Please take a look at the screenshot below 👇 
![image](https://user-images.githubusercontent.com/46839548/217599653-edd0d449-7c7f-4e02-816d-428cc6c0debe.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-08 17:02 UTC, codepantha commented on spec/integration/users_index_spec.rb
> +  end
- [x] Please add a test that shows a redirect to the user's show page when you click on a user as per requirements 👍 
![image](https://user-images.githubusercontent.com/46839548/217584947-79e250fb-10ff-4fa2-99f2-e54924c922e0.png)

2023-02-08 17:02 UTC, codepantha commented on spec/integration/posts_index_spec.rb
> +    end
- [x] Please add a test that shows a redirect to the post's show page when you click on a post as per requirements 👍
![image](https://user-images.githubusercontent.com/46839548/217586605-29a32653-4ee8-4087-844d-96310c5139f1.png)

2023-02-09 14:46 UTC, Oklukeok commented
Hello Reviewer, I added the new tests and you can find in the PR description a new loom video showing the tests.
Thanks!

2023-02-09 15:37 UTC, mukhammadrizooff approved these changes
Hi @Oklukeok, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 
- All tests passed ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-09 15:46 UTC, merged